apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
spec:
  destination:
    namespace: sandbox
    server: https://74.220.25.145
  project: default
  source:
    path: infra/helm
    repoURL: https://github.com/luafanti/spring-boot-debug-app
    targetRevision: main
    plugin:
      env:
        - name: HELM_VALUES
          value: |
             metadata:
              annotations:
                vault.hashicorp.com/agent-inject: "true"
                vault.hashicorp.com/agent-inject-secret-test.txt: 'secret/creds/test'
                vault.hashicorp.com/role: "argocd"
                vault.hashicorp.com/agent-inject-template-test.txt: |
                  {{ "{{" }}- with secret "secret/data/creds/test" -}}
                    export VAULT_SECRET_USER="{{ "{{" }} .Data.data.user }}"
                    export VAULT_SECRET_PASSWORD="{{ "{{" }} .Data.data.password }}"
                  {{ "{{" }}- end }}
            serviceAccount:
              create: true
            image:
              repository: luafanti/spring-boot-debug-app
              tag: main
              pullPolicy: IfNotPresent
            replicaCount: 1
            resources:
              memoryRequest: 256Mi
              memoryLimit: 512Mi
              cpuRequest: 500m
              cpuLimit: 1 
            probes:
              liveness:
                initialDelaySeconds: 15
                path: /actuator/health/liveness
                failureThreshold: 3
                successThreshold: 1
                timeoutSeconds: 3
                periodSeconds: 5
              readiness:
                initialDelaySeconds: 15
                path: /actuator/health/readiness
                failureThreshold: 3
                successThreshold: 1
                timeoutSeconds: 3
                periodSeconds: 5
            ports:
              http:
                name: http
                value: 8080
              management:
                name: management
                value: 8081
            log:
              level:
                spring: "info"
                service: "info"
  syncPolicy: {}
